name: Build and push Docker image

on:
  push:
    branches:
      - 'release/*'
      - 'feature/*' # Remove before merge :)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract release version from branch name
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/heads/release/}

      - name: Build Docker image
        run: | 
          docker build 
          -t qbruynseraede/tf-profile:${{ env.RELEASE_VERSION }} 
          -f build/Dockerfile 
          .

      - name: Push Docker image
        run: docker push qbruynseraede/tf-profile:${{ env.RELEASE_VERSION }}

